disabled_rules: # rule identifiers to exclude from running
  - line_length
  - trailing_whitespace
  - syntactic_sugar
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - CodingChallenge/EZLoadingActivity.swift
